# Base16 Tomorrow Night - alacritty color config
# Chris Kempson (http://chriskempson.com)

[colors]
#draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '#121212'
foreground = '#F1F1F1'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

# Normal colors
[colors.normal]
black = '#1d1f21'
red = '#E06C75'
green = '#98C379'
yellow = '#E5C07B'
blue = '#0184BC'
magenta = '#C678DD'
cyan = '#56B6C2'
white = '#c5c8c6'

# Bright colors
[colors.bright]
black = '#969896'
red = '#de935f'
green = '#282a2e'
yellow = '#373b41'
blue = '#b4b7b4'
magenta = '#e0e0e0'
cyan = '#a3685a'
white = '#ffffff'
